/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ma.fstm.ilisi.presentation;

//import com.toedter.calendar.JDateChooser;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.border.EtchedBorder;
import ma.fstm.ilisi.Controller.*;
import ma.fstm.ilisi.metier.bo.Reservation;
import ma.fstm.ilisi.metier.bo.Station;
import ma.fstm.ilisi.metier.bo.Voyage;

public class Recherche extends javax.swing.JFrame {
    Reservation R;
    //String dateFormatee;

    /**
     * Creates new form Recherche
     */
    public Recherche(Reservation R) {
        R=R;
        initComponents();
        this.setBackground(Color.GRAY);
    }
    public Recherche() {
        R=new Reservation();
        initComponents();
        this.setBackground(Color.GRAY);
        //   dateFormatee="";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        Date = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        Resultat = new javax.swing.JTextArea();
        jOptionPane1 = new javax.swing.JOptionPane();
        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        bouton_ok = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        Date.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        Date.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                DateAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(Date);

        Resultat.setColumns(20);
        Resultat.setRows(5);
        jScrollPane2.setViewportView(Resultat);

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel1.setText("Station de depart");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel2.setText("Station d'arrivee");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        bouton_ok.setText("Rechercher");
        bouton_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_okActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel3.setText("J’achète mon billet :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(bouton_ok)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel2)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                                .addComponent(bouton_ok)
                                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bouton_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_okActionPerformed
        Busway B = new Busway();
        if(!jTextField1.getText().isEmpty() &&!jTextField2.getText().isEmpty()){
            if (!B.recherche(jTextField1.getText(), jTextField2.getText())) {
                return;
            }
            //  LocalDate dateChoisie = dateChooser.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

            // Convertissez la date sélectionnée en une chaîne dans le format "yyyy-MM-dd"
            //    String dateFormatee = dateChoisie.format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));

            this.setVisible(false);
            JFrame jframe = new JFrame("Reservation");
            JButton retour = new JButton("retour");
            jframe.setSize(700,800);
            JPanel VL = new JPanel();

            VL.setLayout(new BoxLayout(VL, BoxLayout.Y_AXIS));
            JPanel columns = new JPanel();
            columns.setMaximumSize(new Dimension(600, 30));
            columns.setBorder(new EtchedBorder(Color.BLACK, Color.WHITE));
            columns.setLayout(new GridLayout(1, 6));
            JLabel NBus, Depart, Prix, Arrivee, Duree;
            NBus = new JLabel("Numero Bus");
            NBus.setForeground(Color.WHITE);
            Depart = new JLabel("Depart");
            Depart.setForeground(Color.WHITE);
            Arrivee = new JLabel("Arrivee");
            Arrivee.setForeground(Color.WHITE);
            Prix = new JLabel("Prix");
            Prix.setForeground(Color.WHITE);
            Duree = new JLabel("Duree");
            Duree.setForeground(Color.WHITE);
            columns.add(NBus);
            columns.add(Depart);
            columns.add(Prix);
            columns.add(Arrivee);
            columns.add(Duree);
            columns.add(new JPanel());

            VL.add(Box.createVerticalStrut(25));
            VL.add(columns);

            //  ArrayList<Voyage> liste_voyage = B.LesVoyagesPourDate(B.VoyageConvonable,dateFormatee);
            ArrayList<Voyage> liste_voyage = B.VoyageConvonable;
            Iterator<Voyage> I = liste_voyage.iterator();

            int i = 1;
            while (I.hasNext()) {
                Voyage V = I.next();

                JButton reserver = new JButton("  Reserver  ");
                JButton details = new JButton("<");
                reserver.setName(Integer.toString(i++));
                reserver.setForeground(Color.WHITE);
                JPanel tmp = new JPanel();
                tmp.setMaximumSize(new Dimension(600, 35));
                tmp.setBorder(new EtchedBorder(Color.BLACK, Color.WHITE));
                tmp.setLayout(new GridLayout(1, 6));
                tmp.add(new JLabel(V.getBus().getNumeroBus() + ""));
                tmp.add(new JLabel(V.premierArret().getKey().getNom() + "\n" + V.premierArret().getValue().getHeureArret()+ ":" + V.premierArret().getValue().getMinArret()));
                tmp.add(new JLabel(V.getPrix() + ""));
                tmp.add(new JLabel(V.dernierArret().getKey().getNom() + "\n" + V.dernierArret().getValue().getHeureArret() + ":" + V.dernierArret().getValue().getMinArret()));
                tmp.add(new JLabel(V.dureeVoyage(new Station(jTextField1.getText()), new Station(jTextField2.getText())) + ""));

                reserver.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        //System.out.println("JE SUIS DANS JFRAME RECHERCHE ???????????????????????????????????????????????????"+V.dureeVoyage(new Station(jTextField1.getText()), new Station(jTextField2.getText())));
                        Voyage v = B.reserver(V,R);
                        Station stationDepart = new Station(jTextField1.getText());
                        Station stationArrive = new Station(jTextField2.getText());
                        Reservation R = new Reservation();
                        R.setReserveVoyage(v);
                        // System.out.println(R);
                        R.setReserveFrom(stationDepart);
                        R.setReserveTo(stationArrive);
                        jframe.setVisible(false);
                        // B.goToPaiment();

                      //  B.GoToAuthentification(R);
                    }

                });
                retour.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        jframe.setVisible(false);
                        new Recherche().setVisible(true);
                    }
                });


                tmp.add(reserver);
                tmp.add(details);
                tmp.setBackground(Color.WHITE);
                if(V.getBus().getNombrePlaceLibre()==0){
                    JLabel PasPlace = new JLabel("occupé");
                    reserver.setText(PasPlace.getText());
                    reserver.setForeground(Color.RED);
                    reserver.setEnabled(false);
                }
                VL.add(tmp);

                details.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        B.construireResultats(V);
                        ArrayList<String> listeDetails = B.getResultats();

                        //tmp.add(new JLabel(V.afficher_Station_Arret() ));

                        // Création du modèle de liste à partir de l'ArrayList
                        DefaultListModel<String> listModel = new DefaultListModel<>();
                        for (String detail : listeDetails) {
                            listModel.addElement(detail);
                        }

                        // Création de la JList avec le modèle
                        JList<String> jList = new JList<>(listModel);

                        // Création de la JFrame pour afficher la liste
                        JFrame frame = new JFrame("Liste des résultats");
                        //frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        frame.setSize(300, 200);

                        // Ajout de la JList dans la JFrame
                        frame.getContentPane().add(new JScrollPane(jList), BorderLayout.CENTER);

                        // Affichage de la JFrame
                        frame.setVisible(true);
                        frame.addWindowListener(new WindowAdapter() {
                            @Override
                            public void windowClosing(WindowEvent e) {
                                super.windowClosing(e);
                                listModel.removeAllElements();
                                listeDetails.clear();
                            }
                        });

                    }
                });

            }
            VL.add(retour);
            jframe.add(VL);
            jframe.setVisible(true);
        }


    }//GEN-LAST:event_bouton_okActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void DateAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_DateAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_DateAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recherche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recherche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recherche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recherche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recherche().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Date;
    private javax.swing.JTextArea Resultat;
    private javax.swing.JButton bouton_ok;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
